<?php
defined('WEKIT_VERSION') or exit(403);
Wind::import('ADMIN:library.AdminBaseController');
/**
 * 后台访问入口
 *
 * generated by upyun.com
 */
class ManageController extends AdminBaseController {
	
	public function beforeAction($handlerAdapter) {
		//TODO do something before all the action
	}
	
	public function run() {
        $config = Wekit::C()->getValues('attachment');
        $accessList = array('0'=>'自动', '1'=>'电信', '2'=>'联通网通', '3'=>'移动铁通');
        $this->setOutput($config,'config');
        $this->setOutput($accessList,'accessList');
	}

	public function doUpyunAction() {
		$config = new PwConfigSet('attachment');
        $open = $this->getInput('upOpen', 'post');
        $access = $this->getInput('upAccess', 'post');
        $url = trim($this->getInput('upUrl', 'post'));
        $dir = trim($this->getInput('upDir', 'post'));
        $bucket = trim($this->getInput('upBucket', 'post'));
        $user = trim($this->getInput('upUser', 'post'));
        $pwd = trim($this->getInput('upPwd', 'post'));
        $type = $open== '1' ? 'upyun' : 'local';
		$attService = Wekit::load('LIB:storage.PwStorage');
        $attService->setStoragesComponents($type);
        $config->set('upyun.open', $open)
            ->set('upyun.access', $access)
			->set('upyun.url', $url)
			->set('upyun.dir', $dir)
			->set('upyun.bucket', $bucket)
			->set('upyun.user', $user)
			->set('upyun.pwd', $pwd)
			->flush();
		$this->showMessage('设置成功');
	}
}

?>
